// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package store is a generated GoMock package.
package store

import (
	gomock "github.com/golang/mock/gomock"
	entities "projects/GoLang-Interns-2022/authorbook/entities"
	reflect "reflect"
)

// MockAuthorStorer is a mock of AuthorStorer interface
type MockAuthorStorer struct {
	ctrl     *gomock.Controller
	recorder *MockAuthorStorerMockRecorder
}

// MockAuthorStorerMockRecorder is the mock recorder for MockAuthorStorer
type MockAuthorStorerMockRecorder struct {
	mock *MockAuthorStorer
}

// NewMockAuthorStorer creates a new mock instance
func NewMockAuthorStorer(ctrl *gomock.Controller) *MockAuthorStorer {
	mock := &MockAuthorStorer{ctrl: ctrl}
	mock.recorder = &MockAuthorStorerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockAuthorStorer) EXPECT() *MockAuthorStorerMockRecorder {
	return m.recorder
}

// Post mocks base method
func (m *MockAuthorStorer) Post(author entities.Author) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Post", author)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Post indicates an expected call of Post
func (mr *MockAuthorStorerMockRecorder) Post(author interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Post", reflect.TypeOf((*MockAuthorStorer)(nil).Post), author)
}

// Put mocks base method
func (m *MockAuthorStorer) Put(author entities.Author, id int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", author, id)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Put indicates an expected call of Put
func (mr *MockAuthorStorerMockRecorder) Put(author, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockAuthorStorer)(nil).Put), author, id)
}

// Delete mocks base method
func (m *MockAuthorStorer) Delete(id int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete
func (mr *MockAuthorStorerMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAuthorStorer)(nil).Delete), id)
}

// IncludeAuthor mocks base method
func (m *MockAuthorStorer) IncludeAuthor(id int) (entities.Author, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncludeAuthor", id)
	ret0, _ := ret[0].(entities.Author)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncludeAuthor indicates an expected call of IncludeAuthor
func (mr *MockAuthorStorerMockRecorder) IncludeAuthor(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncludeAuthor", reflect.TypeOf((*MockAuthorStorer)(nil).IncludeAuthor), id)
}

// MockBookStorer is a mock of BookStorer interface
type MockBookStorer struct {
	ctrl     *gomock.Controller
	recorder *MockBookStorerMockRecorder
}

// MockBookStorerMockRecorder is the mock recorder for MockBookStorer
type MockBookStorerMockRecorder struct {
	mock *MockBookStorer
}

// NewMockBookStorer creates a new mock instance
func NewMockBookStorer(ctrl *gomock.Controller) *MockBookStorer {
	mock := &MockBookStorer{ctrl: ctrl}
	mock.recorder = &MockBookStorerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockBookStorer) EXPECT() *MockBookStorerMockRecorder {
	return m.recorder
}

// GetAllBook mocks base method
func (m *MockBookStorer) GetAllBook() ([]entities.Book, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllBook")
	ret0, _ := ret[0].([]entities.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllBook indicates an expected call of GetAllBook
func (mr *MockBookStorerMockRecorder) GetAllBook() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllBook", reflect.TypeOf((*MockBookStorer)(nil).GetAllBook))
}

// GetBooksByTitle mocks base method
func (m *MockBookStorer) GetBooksByTitle(title string) ([]entities.Book, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBooksByTitle", title)
	ret0, _ := ret[0].([]entities.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBooksByTitle indicates an expected call of GetBooksByTitle
func (mr *MockBookStorerMockRecorder) GetBooksByTitle(title interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBooksByTitle", reflect.TypeOf((*MockBookStorer)(nil).GetBooksByTitle), title)
}

// GetBookByID mocks base method
func (m *MockBookStorer) GetBookByID(id int) (entities.Book, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookByID", id)
	ret0, _ := ret[0].(entities.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBookByID indicates an expected call of GetBookByID
func (mr *MockBookStorerMockRecorder) GetBookByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookByID", reflect.TypeOf((*MockBookStorer)(nil).GetBookByID), id)
}

// Post mocks base method
func (m *MockBookStorer) Post(book *entities.Book) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Post", book)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Post indicates an expected call of Post
func (mr *MockBookStorerMockRecorder) Post(book interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Post", reflect.TypeOf((*MockBookStorer)(nil).Post), book)
}

// Put mocks base method
func (m *MockBookStorer) Put(book *entities.Book, id int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", book, id)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Put indicates an expected call of Put
func (mr *MockBookStorerMockRecorder) Put(book, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockBookStorer)(nil).Put), book, id)
}

// Delete mocks base method
func (m *MockBookStorer) Delete(id int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete
func (mr *MockBookStorerMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBookStorer)(nil).Delete), id)
}
